version: '3'

services:
  vue-portfolio:
    build: .
    container_name: vue-portfolio
    restart: always
    ports:
      - "1000:1000"
    networks:
      - app_network

networks:
  app_laravel:
    driver: bridge
    external: true
